---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokeapi
  labels:
    app.kubernetes.io/name: jokeapi
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jokeapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jokeapi
    spec:
      containers:
        - name: jokeapi
          image: jokeapi
          env:
            - name: GOWON_BROKER
              value: mosquitto:1883
